### ISSUE TITLE
大神开始搞qq了，不管怎么样，先赞一个！

### ISSUE THREAD

**Issue by xieao100** [TKkk-iOSer/QQPlugin-macOS#1]
虽然目前有抢红包的脚本，还是希望大神能来一个！
最好防止消息撤回的时候能和微信小助手一样，提示出谁撤回的，撤回了什么消息。
感谢！

**Comment by xuanll** [comment]
很感谢 @TKkk-iOSer Mac微信小助手非常好用

**Comment by TKkk-iOSer** [comment]
更新了，抢红包还是不了吧，~~懒癌~~ @xuanll 射射 😏
