### ISSUE TITLE
来个自动抢红包

### ISSUE THREAD

**Issue by weilining** [TKkk-iOSer/QQPlugin-macOS#21]
没有抢红包功能感觉很落寞啊

**Comment by TKkk-iOSer** [comment]
不加，毕竟没人给我发红包

**Comment by Cat7373** [comment]
大佬疯狂暗示

**Comment by xiebruce** [comment]
@TKkk-iOSer 抢红包功能我也觉得需要啊，大佬加一个吧哈哈

**Comment by Cat7373** [comment]
# 大佬的暗示
<img src="http://upload-images.jianshu.io/upload_images/965383-cbc86dc1d75a6242.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240" height="250" hspace="50"/>&nbsp;&nbsp;&nbsp;<img src="http://upload-images.jianshu.io/upload_images/965383-76a1c7c91b987e1a.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240" height="250" hspace="50"  />
