### ISSUE TITLE
安装后在Documents文件夹内出现一些文件。

### ISSUE THREAD

**Issue by Butanediol** [TKkk-iOSer/QQPlugin-macOS#6]
<img width="233" alt="image" src="https://user-images.githubusercontent.com/22426749/38688735-6e22949c-3eac-11e8-9e51-ba11a0e643bc.png">

能否解决？

**Comment by TKkk-iOSer** [comment]
是否有装过其他的插件？ 可以去 `/Applications/QQ.app/Contents/MacOS` 看下除了 `QQPlugin.framework`、`QQ_backup`、`QQ`这三个文件还有其他文件没有
